MvcOnlineTicariOtomasyonProject/Models/Siniflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyonProject.Models.Siniflar
{
    public class Personel
    {
        [Key]
        public int PersonelId { get; set; }

        [Display(Name = "Personel Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }

        [Display(Name = "Personel Soyad")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }

        [Display(Name = "Görsel")]
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }

        public ICollection<SatisHareket> SatisHarekets { get; set; }

        public int Departmanid { get; set; }
        public virtual Departman Departman { get; set; }
    }
}

MvcOnlineTicariOtomasyonProject/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonProject.Models.Siniflar;

namespace MvcOnlineTicariOtomasyonProject.Controllers
{
    [Authorize(Roles = "A")]
    public class PersonelController : Controller
    {

        Context c = new Context();
        // GET: Personel
        public ActionResult Index()
        {
            var degerler = c.Personels.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }

        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/image/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/image/" + dosyaadi + uzanti;
            }

            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = c.Personels.Find(id);
            return View("PersonelGetir", prs);
        }

        public ActionResult PersonelGuncelle(Personel p)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/image/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/image/" + dosyaadi + uzanti;
            }
            var prsn = c.Personels.Find(p.PersonelId);
            prsn.PersonelAd = p.PersonelAd;
            prsn.PersonelSoyad = p.PersonelSoyad;
            prsn.PersonelGorsel = p.PersonelGorsel;
            prsn.Departmanid = p.Departmanid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult PersonelListe()
        {
            var sorgu = c.Personels.ToList();
            return View(sorgu);
        }
    }
}

MvcOnlineTicariOtomasyonProject/Views/Personel/Index.cshtml
@using MvcOnlineTicariOtomasyonProject.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        @*<th>ID</th>*@
        <th>PERSONEL ADI</th>
        <th>SOYAD</th>
        <th>DEPARTMAN</th>
        <th>GÖRSEL</th>
        <th>GÜNCELLE</th>
        <th>SATIŞLAR</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            @*<td>@x.PersonelId</td>*@
            <td>@x.PersonelAd</td>
            <td>@x.PersonelSoyad</td>
            <td>@x.Departman.DepartmanAd</td>
            <td>
                <img src="@x.PersonelGorsel" style="width:50px;height:50px;" />
            </td>
            <td><a href="/Personel/PersonelGetir/@x.PersonelId" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelId" class="btn btn-default" style="background-color: darkslateblue; color:white">Detaylar </a></td>

        </tr>

    }
</table>
<a href="/Personel/PersonelEkle/" class="btn btn-dark">Yeni Personel Ekle</a>

MvcOnlineTicariOtomasyonProject/Views/Personel/PersonelEkle.cshtml
@model MvcOnlineTicariOtomasyonProject.Models.Siniflar.Personel

@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Personel Sayfası</h2>
<br />
@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form class="form-group" method="post">
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGorsel)
        @* @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })*@

        <input type="file" name="PersonelGorsel" />
        <br />
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control" })*@
        <br />
        <button class="btn btn-outline-info">KAYDET</button>

    </form>
}

MvcOnlineTicariOtomasyonProject/Views/Personel/PersonelGetir.cshtml
@model MvcOnlineTicariOtomasyonProject.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Personel Güncelleme Ekranı</h2>
<br />
@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.PersonelId)
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGorsel)
        <input type="file" name="PersonelGorsel" />
        <img src="PersonelGorsel" style="width:50px;height:50px;" />
        <br />
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })

        <br />
        <button class="btn btn-outline-warning">Güncelle</button>
    </div>
}

MvcOnlineTicariOtomasyonProject/Views/Personel/PersonelListe.cshtml
@using MvcOnlineTicariOtomasyonProject.Models.Siniflar
@model List<Personel>

@{
    ViewBag.Title = "PersonelListe";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 style="color:darkslategrey;">Personeller</h1>
                    </div>
                </div>
            </div>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row d-flex align-items-stretch">
                        @foreach (var x in Model)
                        {
                            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        @x.Departman.DepartmanAd
                                    </div>
                                    <div class="card-body pt-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@x.PersonelAd @x.PersonelSoyad</b></h2>
                                                <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="@x.PersonelGorsel" alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="/Personel/PersonelGetir/@x.PersonelId" class="btn btn-sm bg-teal">
                                                <i class="fas fa-info-circle"></i>
                                            </a>
                                            <a href="/Departman/DepartmanPersonelSatis/@x.PersonelId" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Satış Geçmişi
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </section>
    </div>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4./plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>