MvcOnlineTicariOtomasyonProject/Controllers/FaturalarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonProject.Models.Siniflar;

namespace MvcOnlineTicariOtomasyonProject.Controllers
{
    [Authorize(Roles = "A")]
    public class FaturalarController : Controller
    {
        // GET: Faturalar

        Context c = new Context();
        public ActionResult Index()
        {
            var fatura = c.Faturalars.ToList();
            return View(fatura);
        }


        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturalars.Find(id);
            return View("FaturaGetir", fatura);
        }

        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var fatura = c.Faturalars.Find(f.FaturaId);
            fatura.FaturaSeriNo = f.FaturaSeriNo;
            fatura.FaturaSiraNo = f.FaturaSiraNo;
            fatura.Saat = f.Saat;
            fatura.Tarih = f.Tarih;
            fatura.TeslimAlan = f.TeslimAlan;
            fatura.TeslimEden = f.TeslimEden;
            fatura.VergiDairesi = f.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaDetay(int id)
        {
            var degerler = c.FaturaKalems.Where(x => x.Faturaid == id).ToList();
            var cr = c.Faturalars.Where(x => x.FaturaId == id).Select(y => y.FaturaSeriNo + " " + y.FaturaSiraNo).FirstOrDefault();
            ViewBag.d = cr;
            return View(degerler);
        }


        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }

        //[HttpPost]
        public ActionResult YeniKalem(FaturaKalem p)
        {
            c.FaturaKalems.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Dinamik()
        {
            Class4 cs = new Class4();
            cs.deger1 = c.Faturalars.ToList();
            cs.deger2 = c.FaturaKalems.ToList();
            return View(cs);
        }

        public ActionResult FaturaKaydet(string FaturaSeriNo, string FaturaSiraNo, DateTime Tarih, string VergiDairesi,
            string Saat, string TeslimEden, string TeslimAlan, string Toplam, FaturaKalem[] kalemler)
        {
            Faturalar f = new Faturalar();
            f.FaturaSeriNo = FaturaSeriNo;
            f.FaturaSiraNo = FaturaSiraNo;
            f.Tarih = Tarih;
            f.VergiDairesi = VergiDairesi;
            f.Saat = Saat;
            f.TeslimEden = TeslimEden;
            f.TeslimAlan = TeslimAlan;
            //f.Toplam = Convert.ToInt32(Toplam);
            c.Faturalars.Add(f);
            foreach (var x in kalemler)
            {
                FaturaKalem fk = new FaturaKalem();
                fk.Aciklama = x.Aciklama;
                fk.BirimFiyat = x.BirimFiyat;
                fk.Faturaid = x.FaturaKalemId;
                fk.Miktar = x.Miktar;
                fk.Tutar = x.Tutar;
                c.FaturaKalems.Add(fk);
            }
            c.SaveChanges();
            return Json("İşlem Başarılı", JsonRequestBehavior.AllowGet);
        }
    }
}

MvcOnlineTicariOtomasyonProject/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyonProject.Models.Siniflar;
using PagedList;
using PagedList.Mvc;

namespace MvcOnlineTicariOtomasyonProject.Controllers
{
    [Authorize(Roles = "A")]
    public class KategoriController : Controller
    {
        // GET: Kategori

        Context c = new Context();
        public ActionResult Index(int sayfa = 1)
        {
            var degerler = c.Kategoris.ToList().ToPagedList(sayfa, 4);
            return View(degerler);
        }

        [HttpGet]//form yüklendigi zaman bu kısım calısması için gereken metot
        public ActionResult KategoriEkle()
        {
            return View();
        }

        [HttpPost]//bir butona tıklanınca çalısacak
        public ActionResult KategoriEkle(Kategori k)
        {
            c.Kategoris.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriSil(int id)
        {
            var Silinecek_ktg = c.Kategoris.Find(id);
            c.Kategoris.Remove(Silinecek_ktg);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var kategori = c.Kategoris.Find(id);
            return View("KategoriGetir", kategori);
        }

        public ActionResult KategoriGuncelle(Kategori k)
        {
            var kategori = c.Kategoris.Find(k.KategoriID);
            kategori.KategoriAd = k.KategoriAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult deneme()
        {
            Class3 cs = new Class3();
            cs.Kategoriler = new SelectList(c.Kategoris, "KategoriID", "KategoriAd");
            cs.Urunler = new SelectList(c.Uruns, "UrunId", "UrunAd");
            return View(cs);
        }
        public JsonResult UrunGetir(int p)
        {
            var urunlistesi = (from x in c.Uruns
                               join y in c.Kategoris
                               on x.Kategori.KategoriID equals y.KategoriID
                               where x.Kategori.KategoriID == p
                               select new
                               {
                                   Text = x.UrunAd,
                                   Value = x.UrunId.ToString()
                               }).ToList();
            return Json(urunlistesi, JsonRequestBehavior.AllowGet);
        }
    }
}

MvcOnlineTicariOtomasyonProject/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Online Ticari Otomasyon | MVC5 </title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <link rel="Shortcut Icon" href="~/image/teamwork.png" type="image/x-icon">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/Kategori/Index/">Ticari Otomasyon</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Aranacak Kelime..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    @*<a class="dropdown-item" href="#">Yardım</a>*@
                    @*<a class="dropdown-item" href="#">Hesabım</a>*@
                    @*<div class="dropdown-divider"></div>*@
                    <a class="dropdown-item" href="/CariPanel/LogOut/">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İŞLEMLER</div>
                        <a class="nav-link" href="/Kategori/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="/Urun/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-paperclip"></i></div>
                            Ürünler
                        </a>
                        @if (User.IsInRole("A"))
                        {
                            <a class="nav-link" href="/Departman/Index/">
                                <div class="sb-nav-link-icon"><i class="fas fa-suitcase"></i></div>
                                Departmanlar
                            </a>
                        }
                        <a class="nav-link" href="/Cari/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Cariler
                        </a>
                        <a class="nav-link" href="/Personel/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-cubes"></i></div>
                            Personeller
                        </a>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-line"></i></div>
                            Grafikler
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Grafik Türleri
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="/Grafik/Index5/">Pie Grafik</a>
                                        <a class="nav-link" href="/Grafik/Index6/">Line Grafik</a>
                                        <a class="nav-link" href="/Grafik/Index7/">Column Grafik</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Rapor & Fatura</div>
                        <a class="nav-link" href="/Satis/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-shopping-cart"></i></div>
                            Satışlar
                        </a>
                        <a class="nav-link" href="/Faturalar/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-credit-card"></i></div>
                            Faturalar
                        </a>
                        <a class="nav-link" href="/Faturalar/Dinamik/">
                            <div class="sb-nav-link-icon"><i class="fas fa-procedures"></i></div>
                            Dinamik Faturalar
                        </a>
                        <a class="nav-link" href="/Personel/PersonelListe/">
                            <div class="sb-nav-link-icon"><i class="fas fa-id-card"></i></div>
                            Personel Tablosu
                        </a>
                        @*<a class="nav-link" href="index.html">
            <div class="sb-nav-link-icon"><i class="fas fa-print"></i></div>
            Giderler
        </a>*@
                        <a class="nav-link" href="/Kargo/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                            Kargolar
                        </a>
                        <a class="nav-link" href="/Urun/UrunListesi/">
                            <div class="sb-nav-link-icon"><i class="fas fa-paperclip"></i></div>
                            Pdf ~ Excel
                        </a>
                        <a class="nav-link" href="/Alertler/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-tags"></i></div>
                            Alertler
                        </a>
                        <a class="nav-link" href="/QR/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-qrcode"></i></div>
                            QR
                        </a>
                        <a class="nav-link" href="/İstatistik/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-signal"></i></div>
                            İstatistikler
                        </a>
                        <a class="nav-link" href="/Galeri/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-camera"></i></div>
                            Galeri
                        </a>
                        <a class="nav-link" href="/UrunDetay/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-eye"></i></div>
                            Ürün Detay
                        </a>

                        <a class="nav-link" href="/İstatistik/KolayTablolar/">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Hızlı Bakış Tabloları
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            @*<footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2019</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer*@>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

MvcOnlineTicariOtomasyonProject/Views/Shared/_CariLayout.cshtml
@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Online Ticari Otomasyon | MVC5 </title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />

    <link rel="Shortcut Icon" href="~/image/teamwork.png" type="image/x-icon">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/CariPanel/Index/">Ticari Otomasyon <br /> Cari Paneli</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Aranacak Kelime..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Cari Panel Menüsü</div>
                        <a class="nav-link" href="/CariPanel/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Profilim
                        </a>
                        <a class="nav-link" href="/CariPanel/Siparislerim/">
                            <div class="sb-nav-link-icon"><i class="fas fa-shopping-bag"></i></div>
                            Siparişlerim
                        </a><a class="nav-link" href="/CariPanel/KargoTakip/">
                            <div class="sb-nav-link-icon"><i class="fas fa-truck"></i></div>
                            Kargo Takibi
                        </a>
                        <a class="nav-link" href="/CariPanel/GelenMesajlar/">
                            <div class="sb-nav-link-icon"><i class="fas fa-mail-bulk"></i></div>
                            Mesajlar
                        </a>
                        <a class="nav-link" href="/CariPanel/LogOut/">
                            <div class="sb-nav-link-icon"><i class="fas fa-sign-out-alt"></i></div>
                            Çıkış
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

MvcOnlineTicariOtomasyonProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC5</title>

    <link rel="Shortcut Icon" href="~/image/teamwork.png" type="image/x-icon">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fatura İşlemleri", "Dinamik", "Faturalar", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Faturalar", "Dinamik", "Faturalar")</li>
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Kategori")</li>
                    <li>@Html.ActionLink("Yardım", "Yardım", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>